development:
  mailer_domain:  <%= ENV.fetch("MAILER_DOMAIN") %>
  user_name:      <%= ENV.fetch("USER_NAME") %>
  password:       <%= ENV.fetch("PASSWORD") %>
  address:        <%= ENV.fetch("ADDRESS") %>
  domain:         <%= ENV.fetch("DOMAIN") %>
  port:           <%= ENV.fetch("PORT") %>
  authentication: <%= ENV.fetch("AUTHENTICATION") %>
